// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rezeixylbywxaqaoloux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlemVpeHlsYnl3eGFxYW9sb3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTkzMjgsImV4cCI6MjA2NTQ3NTMyOH0.MvG7erI3uQrUSljLqLQ8-pj5xhifKzf_1p55dGIC99Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);